# Generated by Django 3.0.3 on 2020-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
