# Generated by Django 3.0.3 on 2020-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Travel', '0002_auto_20200610_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='pics_hotel')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
