# Generated by Django 3.0.3 on 2020-06-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Travel', '0003_hotellist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotellist',
            name='review',
            field=models.IntegerField(default=1),
        ),
    ]
