# Generated by Django 3.0.3 on 2020-06-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Travel', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_name',
            new_name='prefer_hotel',
        ),
    ]
